name: Preference
version: '${project.version}'
main: me.natertot.preference.Preference
api-version: 1.12.2
depend:
  - ServerUtils
commands:
  pref:
    description: Opens the inventory /pref
    aliases: [preference, preferences]

  prefadmin:
    description: Admin command
    permission: preference.admin
    permission-message: Cannot use this unless you are an admin

